version: "3.7"
services:
  web:
    build: './gateway'
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/planner

#  rq-dashboard:
#    image: jaredv/rq-docker:0.0.2
#    command: rq-dashboard -H rq-server
#    ports:
#      - 9181:9181
#
#  rq-mail:
#    image: jaredv/rq-docker:0.0.2
#    command: rq mail -u redis://rq-server:6379 high normal low
#    deploy:
#      replicas: 3
#
#  rq-server:
#    image: redis:alpine
#    ports:
#      - 6379:6379

#  rabbitmq:
#    image: rabbitmq:latest
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - "5672:5672"

#  flower:
#    image: mher/flower
#    command: [ "flower", "--broker=redis://redis:6379/0", "--port=8888" ]
#    ports:
#      - 8888:8888

#  celery:
#    build: .
#    image: &img mail
#    command: [ celery, mail, --app=rq.app, --pool=gevent, --loglevel=INFO ]
#    links:
#      - rabbitmq
#    environment:
#      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672


#  celery_worker:
#    hostname: rabbitmq
#    command: celery -A public mail -l INFO
#    ports: [ ]
#    networks:
#      - main
#    depends_on:
#      - rabbitmq
#    environment:
#      #- RABBITMQ_DEFAULT_USER=admin
#      #- RABBITMQ_DEFAULT_PASS=password
#      - CELERY_BROKER=amqp://guest:guest@rabbitmq

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  mail:
    build: "./mail"
    command: "celery -A rq worker -l INFO"
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
#
#  flower:
#    build: ./
#    command: python -m flower -A tasks
#    ports:
#      - 5555:5555
#    environment:
#      CELERY_BROKER_URL: redis://redis
#      CELERY_RESULT_BACKEND: redis://redis

  flower2:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - mail